name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix: # will create combinations based on our values (6 combinations for the below values)
        node-version: [12,14,16]
        operating-system: [ubuntu-latest, windows-latest]
        include: # add a standalone combination
          - node-version: 18
            operating-system: ubuntu-latest
        exclue:
          - node-version: 12 # to exclue a combination
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }} #this will run the jobs 2 times one for ubuntu and one for windows with the node-version combination (total 6 jobs)
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build